source "https://rubygems.org"

gem "base64"
gem "csv"
gem "cgi"
gem "concurrent-ruby"
gem "foreman"
gem "jekyll", "4.3.3"
gem "jekyll-sitemap"
gem "logger"
gem "nokogiri"
gem "standard"
gem "minitest"
gem "ostruct"
