[daemons.jekyll]
run = "bundle exec jekyll build -w --future --unpublished --drafts --trace --config _config.yml,_config_dev.yml"
retry = 0
ready_delay = 3
auto_bump_port = false
port_bump_attempts = 10

[daemons.static]
run = "mise exec -- caddy run --config Caddyfile"
retry = 0
ready_http = "https://localhost/"
expected_port = [443]
auto_bump_port = false
port_bump_attempts = 10
depends = ["jekyll"]

[daemons.worker]
run = "./node_modules/.bin/wrangler dev --port 8787"
retry = 0
ready_http = "http://localhost:8787/"
expected_port = [8787]
auto_bump_port = false
port_bump_attempts = 10
depends = ["static"]
